#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server:

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
fp="$1"
sip="$2"
un="$3"
sk="$4"

scp -o StrictHostKeyChecking=no -i "$sk" "$fp" "$un@$sip:~/"

if [ $? -eq 0 ]; then
    echo "File transferred successfully to $un@$sip"
else
    echo "File transfer failed"
fi
