#!/usr/bin/env bash
#instaling nginx

sudo apt-get update -y
sudo apt-get install nginx -y

sudo echo "Hello World!" > /var/www/html/index.html

sudo sed -i 's/^\(listen\s*\)[0-9]*\s*;$/\180;/' /etc/nginx/sites-available/default

sudo service nginx restart
