#!/usr/bin/env bash
# redirecting

if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get install -y nginx
fi

echo "server {
    listen 80;
    server_name _;i

    location / {
        return 200 'Hello World!';

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" >> /etc/nginx/sites-available/redirect

ln -sf /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

service nginx reload
