#!/usr/bin/env bash
# redirecting

if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

echo "server {
    listen 80;
    server_name _;

    location / {
        return 200 'Hello World!';

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" >> /etc/nginx/sites-available/redirect_me

sudo ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo service nginx reload
