#!/usr/bin/env bash
#install and configure HAproxy in a load balancer server

sudo apt-get install -y haproxy
echo"
frontend f
	mode http
	bind :80
	use_backend b

backend b
	mode http
	balance roundrobin
	server web-01 54.87.206.27:80 check
	server web-02 107.23.163.211:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
