#!/usr/bin/env bash
# displaying numbers from 1 to 100 and display fizz if the num is devisable by 3 and buzz if the num is devisable by 5
for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
